In [1]:
import numpy as np

In [17]:
inputs = np.array([
    [0, 0],
    [0, 1],
    [1, 0],
    [1, 1]
])
inputs

array([[0, 0],
       [0, 1],
       [1, 0],
       [1, 1]])

In [34]:
targets = np.array([[0], [0], [0], [1]])
targets

array([[0],
       [0],
       [0],
       [1]])

In [15]:
nIn = 2
nIn

2

In [16]:
nOut = 1
nOut

1

In [12]:
nData = inputs.shape[0]
nData

4

In [13]:
inputs.shape

(4, 2)

In [19]:
weights = np.random.rand(nIn + 1, nOut) * 0.1 - 0.05
weights

array([[ 0.0303947 ],
       [ 0.01626871],
       [-0.00965578]])

In [20]:
inputs = np.concatenate((inputs, -np.ones((nData, 1))), axis=1)
inputs

array([[ 0.,  0., -1.],
       [ 0.,  1., -1.],
       [ 1.,  0., -1.],
       [ 1.,  1., -1.]])

In [22]:
activations = np.dot(inputs, weights)
activations

array([[0.00965578],
       [0.02592449],
       [0.04005049],
       [0.05631919]])

In [29]:
targets

array([0, 0, 0, 1])

In [27]:
outputs = np.where(activations > 0, 1, 0)
outputs

array([[1],
       [1],
       [1],
       [1]])

In [47]:
weights += learning_rate * np.dot(inputs.T, (targets - outputs))
weights

array([[0.5303947 ],
       [0.51626871],
       [0.49034422]])

In [49]:
weights

array([[0.5303947 ],
       [0.51626871],
       [0.49034422]])

New

In [3]:
import numpy as np

In [4]:
inputs = np.array([
    [0, 0, 0],
    [0, 0, 1],
    [0, 1, 0],
    [0, 1, 1],
    [1, 0, 0],
    [1, 0, 1],
    [1, 1, 0],
    [1, 1, 1]
])

In [5]:
targets = np.array([[0], 
                    [0], 
                    [0], 
                    [0],
                    [0], 
                    [0],
                    [0],
                    [1]])

In [6]:
nIn = inputs.shape[1]
nIn

3

In [8]:
nOut = targets.shape[1]
nOut

1

In [ ]:
#nIn = 3

In [ ]:
#nOut = 1

In [9]:
nData = inputs.shape[0]

In [10]:
weights = np.random.rand(nIn + 1, nOut) * 0.1 - 0.05

In [11]:
inputs = np.concatenate((inputs, -np.ones((nData, 1))), axis=1)

In [12]:
learning_rate = 0.25
max_iters = 100

In [13]:
def accuracy(y_pred, y_test):
    return (y_pred==y_test).mean()

In [14]:
for i in range(max_iters):
    activations = np.dot(inputs, weights)
    outputs = np.where(activations > 0, 1, 0)
    weights += learning_rate * np.dot(inputs.T, (targets - outputs))
    acc = accuracy(outputs, targets)
    #if (i+1)%100 == 0:
    print("iteration: ", i+1)
    print(acc)
    if acc == 1.0:
        print(outputs)
        print(weights)
        break

iteration:  1
0.375
iteration:  2
0.875
iteration:  3
0.875
iteration:  4
0.875
iteration:  5
0.75
iteration:  6
0.875
iteration:  7
0.875
iteration:  8
0.5
iteration:  9
0.875
iteration:  10
0.875
iteration:  11
1.0
[[0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]]
[[0.29316292]
 [0.25994391]
 [0.45532966]
 [0.97552303]]
